version: "3"
services:
  web:
    build: ./web
    user: node
    volumes:
      - ./web:/web
      - /web/node_modules
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
    command: pm2-docker start index.js --watch

  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx/disqus-clone.template:/etc/nginx/conf.d/disqus-clone.template
    ports:
      - "8080:80"
    links:
      - web
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/disqus-clone.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  # redis:
  #   image: redis:3.2-alpine
